Make it available in Android devices

diff --git a/common b/common
--- a/common
+++ b/common
@@ -21,6 +21,32 @@ chroot_maybe_add_mount() {
   fi
 }
 
+try_mkdir() {
+  if [[ ! -d $1 ]]; then
+    warning "$1 don't exist, try mkdir it firstly!"
+    mkdir -p "$1"
+  fi
+}
+
+chroot_try_add_mount() {
+  # chroot_try_add_mount will mount $dest to $chrootdir$dest when mount failed
+  local src=$1
+  local dest=$2
+  shift 2
+  local args="${@}"
+
+  try_mkdir $dest
+  chroot_add_mount $src $dest $args 2>/dev/null
+  
+  if [[ $? -ne 0 ]]; then
+    local old_src=$src
+    src="${dest#$chrootdir}"
+    warning "mount $old_src failed! try mount -o bind $src $dest instead!"
+    try_mkdir $src
+    chroot_bind_device $src $dest
+  fi
+}
+
 chroot_setup() {
   CHROOT_ACTIVE_MOUNTS=()
   [[ $(trap -p EXIT) ]] && die '(BUG): attempting to overwrite existing EXIT trap'
@@ -30,10 +56,10 @@ chroot_setup() {
   chroot_add_mount sys "$1/sys" -t sysfs -o nosuid,noexec,nodev,ro &&
   ignore_error chroot_maybe_add_mount "[[ -d '$1/sys/firmware/efi/efivars' ]]" \
       efivarfs "$1/sys/firmware/efi/efivars" -t efivarfs -o nosuid,noexec,nodev &&
-  chroot_add_mount udev "$1/dev" -t devtmpfs -o mode=0755,nosuid &&
-  chroot_add_mount devpts "$1/dev/pts" -t devpts -o mode=0620,gid=5,nosuid,noexec &&
-  chroot_add_mount shm "$1/dev/shm" -t tmpfs -o mode=1777,nosuid,nodev &&
-  chroot_add_mount /run "$1/run" --bind --make-private &&
+  chroot_try_add_mount udev "$1/dev" -t devtmpfs -o mode=0755,nosuid &&
+  chroot_try_add_mount devpts "$1/dev/pts" -t devpts -o mode=0620,gid=5,nosuid,noexec &&
+  chroot_try_add_mount shm "$1/dev/shm" -t tmpfs -o mode=1777,nosuid,nodev &&
+  chroot_add_mount run "$1/run" -t tmpfs -o nosuid,nodev,mode=0755 &&
   chroot_add_mount tmp "$1/tmp" -t tmpfs -o mode=1777,strictatime,nodev,nosuid
 }
 
diff --git a/pacstrap.in b/pacstrap.in
--- a/pacstrap.in
+++ b/pacstrap.in
@@ -72,7 +72,11 @@ pacstrap() {
 
   msg 'Installing packages to %s' "$newroot"
   if ! $pid_unshare pacman -r "$newroot" "${pacman_args[@]}"; then
-    die 'Failed to install packages to new root'
+    warning "Failed to $pid_unshare pacman -r "$newroot" "${pacman_args[@]}""
+    warning "Try pacman -r "$newroot" "${pacman_args[@]}" without $pid_unshare!"
+    if ! pacman -r "$newroot" "${pacman_args[@]}";then
+      die 'Failed to install packages to new root'
+    fi
   fi
 
   if (( copymirrorlist )); then
